import streamlit as st
import tensorflow as tf
import numpy as np

from PIL import Image
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Load model
model = tf.keras.models.load_model(
    "final_brain_tumor_model.keras"
)

classes = [
    "Glioma",
    "Meningioma",
    "No Tumor",
    "Pituitary"
]

st.title("🧠 Brain Tumor Detection using Deep Learning")

st.info(
    "Please upload a Brain MRI image (JPG, JPEG, PNG). Predictions on non-MRI images may be unreliable."
)

st.markdown("""
This system uses a MobileNetV2 Deep Learning model
to classify MRI scans into:

- Glioma
- Meningioma
- Pituitary
- No Tumor
""")

uploaded_file = st.file_uploader(
    "Upload MRI Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(image, caption="Uploaded MRI Scan", width=300)

    img = image.resize((224,224))
    img = np.array(img)
    img = preprocess_input(img)
    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img, verbose=0)

    probs = prediction[0]

    predicted_class = classes[np.argmax(prediction)]

    confidence = np.max(prediction) * 100

    # Analysis Result
    st.write("## Analysis Result")

    if predicted_class == "No Tumor":

        st.success(
            f"""
            ✅ The model predicts that no brain tumor is present.

            Confidence Score: {confidence:.2f}%
            """
        )

    else:

        st.error(
            f"""
            ⚠️ The model predicts the presence of a brain tumor.

            Detected Tumor Type: {predicted_class}

            Confidence Score: {confidence:.2f}%
            """
        )

    # Confidence Bar
    st.progress(float(confidence)/100)

    # Tumor Description
    if predicted_class == "Glioma":
        st.info(
            "Glioma is a tumor that occurs in the brain and spinal cord."
        )

    elif predicted_class == "Meningioma":
        st.info(
            "Meningioma develops from the membranes surrounding the brain."
        )

    elif predicted_class == "Pituitary":
        st.info(
            "Pituitary tumors develop in the pituitary gland."
        )

    else:
        st.info(
            "No tumor characteristics were detected in the uploaded MRI scan."
        )

    # Class Probabilities
    st.write("## Class-wise Probability")

    for cls, prob in zip(classes, probs):
        st.write(f"**{cls}:** {prob*100:.2f}%")

    # Disclaimer
    st.warning(
        """
        Disclaimer:
        
        This result is generated by an AI model trained on MRI images.
        It is intended for educational and research purposes only and
        should not be considered a medical diagnosis.
        
        Please consult a qualified healthcare professional for clinical evaluation.
        """
    )